nama=input("Masukkan Nama: ")
nim=input("Masukka NIM: ")
kelas_paralel=input("Masukkan Kelas Pararel: ")
ttl=input("Masukan Tempat/Tanggal Lahir (Kota/dd-mm-yyyy): ")
alamat=input("Masukan Alamat: ")
hobby=input("Masukan Hobby: ")
no_hp=input("Masukan No. HP: ")

print(f"\nNama                :{nama}")
print(f"NIM                 :{nim}")
print(f"Kelas Paralel       :{kelas_paralel}")
print(f"Tempat/Tanggal Lahir:{ttl}")
print(f"Alamat              :{alamat}")
print(f"Hobby               :{hobby}")
print(f"No.HP               :{no_hp}") 
